# Generated by Django 4.2 on 2025-12-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_academicyear_alter_event_location_alter_event_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_past',
            field=models.BooleanField(default=False),
        ),
    ]
