# Generated by Django 4.2 on 2025-12-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_event_event_date_event_is_past'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='description',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.PositiveIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')], unique=True),
        ),
    ]
